# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails-logger-ext}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nclark"]
  s.date = %q{2010-11-18}
  s.description = %q{simple rails extension providing Rails.logger.pp and Rails.logger.achtung! ... YA HEARD}
  s.email = %q{nclark@thrownproject.org}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "lib/rails-logger-ext.rb",
    "lib/rails-logger-ext/extensions.rb",
    "lib/rails-logger-ext/railtie.rb"
  ]
  s.homepage = %q{http://github.com/nclark/rails-logger-ext}
  s.licenses = ["WTFPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{simple rails extension providing Rails.logger.pp and Rails.logger.achtung!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

